### ISSUE TITLE
Add dark mode support

### ISSUE THREAD

**Issue by mseele** [rust-lang/blog.rust-lang.org#1184]
I often read the rust blog in the dark and always wonder why there is no dark mode.

It would be really cool if the rust blog had a dark mode. Is there anything against it?

**Comment by Turbo87** [comment]
@mseele do you want to help implement it? :)

**Comment by mseele** [comment]
@Turbo87 if anyone can help with the visual design (where to place the light/dark button, choice of colors, etc.) I can take a look

**Comment by Turbo87** [comment]
unfortunately, that's the same problem we have with crates.io. we have the dev skills to implement it, but visual design is not a strong skill for us 😅

**Comment by fenhl** [comment]
Here's a quick user style I threw together that can be used until this feature is implemented:

```css
@media (prefers-color-scheme: dark) {
    body {
        background-color: black;
        filter: invert(1.0);
    }
}
```
