### ISSUE TITLE
Line spacing?

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/blog.rust-lang.org#269]
from https://news.ycombinator.com/item?id=17980163

@jonhoo , this is due to your tweaks here: https://github.com/rust-lang/blog.rust-lang.org/pull/263

any idea how we should fix this?

**Comment by jonhoo** [comment]
That's really weird -- it looks fine here too. This suggests there's a `line-height` property somewhere that's affecting the code samples, but I can't find one in our code. When `line-height` isn't set, underscores and the like should render just fine. It's a little hard to debug this now that it's been reverted. The quick-fix would be to add `line-height: 1.5` to the `pre, code` rule in `_sass/_base.css`.

**Comment by reiner-dolp** [comment]
@jonhoo I have added additional screenshots for explanation. Lines are rendered one after another, if the line-spacing becomes to tight through user settings the background of the current line will hide the bottom of the previous line.

#269 can be reapplied. Just rewrite the Code Formatting section to

```css
pre,
code {
    font-size: 15px;
    border: 1px solid $grey-color-light;
    border-radius: 3px;
    background-color: #eef;
}

code {
    padding: 1px 5px;
}

pre code { background: transparent; }
```
