### ISSUE TITLE
Blog post titles in new design are hard to read due to increased font-weight

### ISSUE THREAD

**Issue by krdln** [rust-lang/blog.rust-lang.org#309]
In the new design, we're using "Alfa Slab One" font, which is itself bold, and then the weight of it is increased for `h2`

```css
h3, .post h2, header h2 {
  display: inline-block;
  font-weight: 800;
  font-size: 1.8em;
  letter-spacing: normal; }
```

As a result, a lot of the serifs are merged which makes the font very hard to read (Δnnouncing Bust?):
![announcing800](https://user-images.githubusercontent.com/3074996/49604547-70539c00-f98e-11e8-9957-3fcd767ba3fc.png)

For comparison, here's how it would look without `font-weight: 800`:
![annoucing-default](https://user-images.githubusercontent.com/3074996/49604568-7a759a80-f98e-11e8-9435-0ff060304053.png)

---

Firefox 63 @ Ubuntu 18.04
