### ISSUE TITLE
Remove the $ prefix from all bash snippets

### ISSUE THREAD

**Issue by styfle** [rust-lang/blog.rust-lang.org#369]
The `$` prefix gets [annoying](https://twitter.com/styfle/status/1099352083881492480) when copy/pasting a bash snippet.

Consider removing the `$` from the code and using CSS instead.

```css
code.language-bash:before {
    content: '$ ';
}
```
